"""add_document_question_fields

Revision ID: d3ca9d13a6ec
Revises: d2e3f4a5b6c7
Create Date: 2026-06-02 17:14:04.549053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3ca9d13a6ec'
down_revision: Union[str, Sequence[str], None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('gpt_status', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_classroom_id'), 'documents', ['classroom_id'], unique=False)
    op.drop_table('roles')
    op.drop_constraint(op.f('classes_code_key'), 'classes', type_='unique')
    op.add_column('questions', sa.Column('classroom_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('document_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('created_by_teacher', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_questions_classroom_id'), 'questions', ['classroom_id'], unique=False)
    op.create_foreign_key(None, 'questions', 'users', ['created_by_teacher'], ['id'])
    op.create_foreign_key(None, 'questions', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'classes', ['classroom_id'], ['id'])
    op.drop_index(op.f('ix_teacher_classrooms_classroom_id'), table_name='teacher_classrooms')
    op.drop_index(op.f('ix_teacher_classrooms_teacher_id'), table_name='teacher_classrooms')
    op.drop_index(op.f('ix_users_teacher_code_unique'), table_name='users', postgresql_where='(teacher_code IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_teacher_code_unique'), 'users', ['teacher_code'], unique=True, postgresql_where='(teacher_code IS NOT NULL)')
    op.create_index(op.f('ix_teacher_classrooms_teacher_id'), 'teacher_classrooms', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_classrooms_classroom_id'), 'teacher_classrooms', ['classroom_id'], unique=False)
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_classroom_id'), table_name='questions')
    op.drop_column('questions', 'is_approved')
    op.drop_column('questions', 'created_by_teacher')
    op.drop_column('questions', 'document_id')
    op.drop_column('questions', 'classroom_id')
    op.create_unique_constraint(op.f('classes_code_key'), 'classes', ['code'], postgresql_nulls_not_distinct=False)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey')),
    sa.UniqueConstraint('name', name=op.f('roles_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_documents_classroom_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
